---
framework: jest
preRun:
  command:
    - yarn install
    - yarn build
    - yarn run
preMerge:
  pattern:
    - "./packages/**/test/*.test.{ts,tsx}"
postMerge:
  pattern:
    - "./packages/**/test/*.test.{ts,tsx}"
postRun:
  command:
    - node --version
configFile: jest.config.js
version: 1.2
